# Generated by Django 6.0.2 on 2026-03-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='imageGroup',
            new_name='image_group',
        ),
    ]
